using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;

// will handle all inputs abd pass them out via Actions

public class InputManager : MonoBehaviour, Inputs.IPlayerActions
{
    #region Instance
    private static InputManager instance;

    
    public static InputManager Instance
    {
        get
        {
            if (instance == null)
            {
                instance = FindObjectOfType<InputManager>();
                if (instance == null)
                {
                    GameObject obj = new GameObject("InputManager");
                }
            }
            return instance;
        }
    }
    #endregion

   
    // Reference to the Inputs class, which is generated by the Input System
    private Inputs inputs;

    void Awake()
    {

        // Initialize the GameInput instance
        inputs = new Inputs();

        // Enable the Player action map to start listening for player input
        inputs.Player.Enable();

        // Set this script (InputManager) as the callback handler for player actions
        // This ensures methods like OnMove are called when the respective inputs are performed
        inputs.Player.SetCallbacks(this);
   
        #region Singleton
        if (instance == null)
        {
            instance = this;
            DontDestroyOnLoad(gameObject);
        }
        else
        {
            Destroy(gameObject);
        }
        #endregion
    }








    public void OnMove(InputAction.CallbackContext context)
    {
        MoveEvent?.Invoke(context.ReadValue<Vector2>());
        Debug.Log("Move Input Performed");
    }

    public void OnPause(InputAction.CallbackContext context)
    {
        if (context.started)
        {
            PauseEvent?.Invoke();
            Debug.Log("Pause Input Performed");
        }
    }




    #region Input Events

    public event Action PauseEvent;
    public event Action<Vector2> MoveEvent;

    #endregion



}


